language: rust
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt --all -- --check
  # - cargo clippy
  - cargo build
  - cargo test
cache: cargo
