[package]
name = "test262_parser_tests"
version = "0.1.0"
authors = ["retep007 <peter.hrvola@airtame.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
glob = "0.2.11"
proc-macro2 = "0.4"
quote = "0.6.10"
